<a href="https://colab.research.google.com/github/omkarmohite123/omkarmohite123/blob/main/100_questions_on_Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>








 # Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
print(np.__version__)
np.show_config()


1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [3]:
x = np.zeros(10)
print(x)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [4]:
x = np.arange(10)
print(x)
print("size ==",x.size)
print("memory size ==",x.itemsize)

[0 1 2 3 4 5 6 7 8 9]
size == 10
memory size == 8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [5]:
import numpy as np
np.info(np.add)


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [6]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [7]:
x=np.arange(10,49)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [28]:
x[::-1]

array([10,  9,  8, -7, -6, -5, -4,  3,  2,  1,  0])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [9]:
x=np.arange(9).reshape(3, 3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [10]:
x=[1,2,0,0,4,0]
a=np.nonzero(x)
print(a)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [11]:
x=np.eye(3,3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [12]:
x=np.random.random((3,3,3))
print(x)

[[[0.83194256 0.97077081 0.21927471]
  [0.34134107 0.20360051 0.85567405]
  [0.23955597 0.28124611 0.61497487]]

 [[0.43625248 0.02332537 0.77682939]
  [0.08851745 0.20307731 0.36402381]
  [0.55210424 0.11483997 0.34035424]]

 [[0.33286599 0.91137503 0.08513585]
  [0.196019   0.88293388 0.09264325]
  [0.92501597 0.34784756 0.88539369]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [13]:
x=np.random.random((10,10))
print("10*10 array ==\n",x)
print("min of array\n",x.min())
print("max of array\n",x.max())

10*10 array ==
 [[0.8619945  0.68486616 0.50081117 0.27923278 0.90540578 0.42329632
  0.33932395 0.82566471 0.83083717 0.16381494]
 [0.57081191 0.89831837 0.18815356 0.28162027 0.54450874 0.31980387
  0.89103063 0.84484726 0.31643132 0.86321393]
 [0.19528925 0.57374094 0.44804114 0.1968218  0.00549381 0.23242812
  0.00698883 0.82269039 0.53688285 0.81740402]
 [0.96189852 0.30186626 0.05298586 0.68171245 0.02238879 0.38997607
  0.78231445 0.7579921  0.27583272 0.3072894 ]
 [0.14301266 0.76167924 0.97097203 0.76363945 0.03734269 0.07813611
  0.90459812 0.66246434 0.82585316 0.67020375]
 [0.17423726 0.16381331 0.08559889 0.31595385 0.94398856 0.6933335
  0.32775765 0.63436809 0.52902031 0.47930937]
 [0.79963776 0.34953804 0.92834994 0.29045124 0.53691542 0.81978931
  0.93005395 0.92922099 0.11566646 0.79556654]
 [0.7001809  0.00327737 0.43740948 0.65533942 0.04785878 0.07035601
  0.91757283 0.29238059 0.62247551 0.1015419 ]
 [0.79656519 0.35422995 0.85957407 0.65898176 0.8288184  0.772541

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)


```
`# This is formatted as code`
```



In [14]:
x=np.random.random((30))
print("random vector of size 30\n",x)
print("mean value is\n",x.mean())

random vector of size 30
 [0.890412   0.08373019 0.59778002 0.15227509 0.07905165 0.20334963
 0.7905158  0.05023918 0.70049418 0.20081653 0.58020064 0.94457326
 0.7163373  0.94845241 0.84960956 0.53728402 0.21558323 0.71487022
 0.18107456 0.1014801  0.69970629 0.81199104 0.58842864 0.63202551
 0.08757571 0.3080137  0.69788616 0.89507401 0.0434115  0.51867086]
mean value is
 0.49403043342471187


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [15]:
x=np.ones((10,10))
x[1:-1,1:-1] = 0
print(x)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [16]:
x = np.ones((5,5))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [17]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [18]:
x = np.diag(1+np.arange(4),k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [19]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [20]:
print(np.unravel_index(99,(6,7,8)))


(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [21]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [22]:
x= np.random.random((5,5))
print("value of random matrix ==",x)
min=x.min()
max=x.max()
k=(x-min)/(max-min)
print("ans of  (x-min)/(max-min)\n",k)


value of random matrix == [[0.38615059 0.11585686 0.04549982 0.73788938 0.59280386]
 [0.08317847 0.51341912 0.29870909 0.16291271 0.55304872]
 [0.4402699  0.66041469 0.61020235 0.61605286 0.78621438]
 [0.23865724 0.60775471 0.4831512  0.64941303 0.80567267]
 [0.10970208 0.49804309 0.67370203 0.86683116 0.0876394 ]]
ans of  (x-min)/(max-min)
 [[0.41475438 0.08566219 0.         0.84300881 0.66636206]
 [0.0458751  0.56970833 0.30829125 0.14295436 0.61795876]
 [0.48064656 0.74868063 0.68754533 0.69466853 0.90184621]
 [0.235176   0.68456524 0.53285606 0.73528572 0.92553738]
 [0.07816853 0.55098747 0.76485844 1.         0.05130643]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [23]:
import numpy as np

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [24]:
x = np.ones((5,3)) @ np.ones((3,2))
print(x)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [25]:
x = np.arange(11)
x[(3 < x) & (x < 8)] *= -1
print(x)


[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [26]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [27]:
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)


[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[[False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]]
[[0.+0.j 0.+1.j 0.+0.j 0.+1.j 0.+0.j 0.+1.j 0.+0.j 0.+1.j]
 [0.+1.j 0.+0.j 0.+1.j 0.+0.j 0.+1.j 0.+0.j 0.+1.j 0.+0.j]
 [0.+0.j 0.+1.j 0.+0.j 0.+1.j 0.+0.j 0.+1.j 0.+0.j 0.+1.j]
 [0.+1.j 0.+0.j 0.+1.j 0.+0.j 0.+1.j 0.+0.j 0.+1.j 0.+0.j]
 [0.+0.j 0.+1.j 0.+0.j 0.+1.j 0.+0.j 0.+1.j 0.+0.

ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
x = np.random.uniform(-10,+10,10)
print("random x\n",x)
print(np.copysign(np.ceil(np.abs(x)), x))



#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
x1 = np.random.randint(0,8,10)
x2 = np.random.randint(0,8,10)
print("common values are",np.intersect1d(x1,x2))


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
#using np.seterr
defaults = np.seterr(all="ignore")
x = np.ones(1) / 0
print(x)
#back to sanity
_ = np.seterr(**defaults)
#using np.errstate
with np.errstate(all="ignore"):
    np.arange(3) / 0


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
np.sqrt(-1) == np.emath.sqrt(-1)


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [30]:
yesterday = np.datetime64('today') - np.timedelta64(1)
print("yesterday date ==",yesterday)
today     = np.datetime64('today')
print("today date ==",today)
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print("tomarrow date",tomorrow)

yesterday date == 2022-08-18
today date == 2022-08-19
tomarrow date 2022-08-20


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(3)*1
print("A\n",A)
B = np.ones(3)*2
print("B\n",B)
add=np.add(A,B,out=B)
print("add (A+B)\n",add)
divide =np.divide(A,2,out=A)
print("(A/2)\n",divide)
negative=np.negative(A,out=A)
print("-1 * (A/2)\n",negative)
multiply=np.multiply(A,B,out=A)
print("((A+B)*(-A/2))\n",multiply)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
x= np.random.uniform(0,10,10)
print("random array\n",x)
print("% method\n",x - x%1)
print("using floor\n",np.floor(x))
print("using ceil\n",np.ceil(x))
print("using astype\n",x.astype(int))
print("using trunc\n",np.trunc(Z))

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [31]:
x=np.zeros((5,5))
x+=np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [32]:
def generate():
    for x in range(10):
        yield x
x = np.fromiter(generate(),dtype=float,count=-1)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [33]:
x = np.linspace(0,1,11,endpoint=False)[1:]
print(x)


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [34]:
x = np.random.random(10)
x.sort()

print(x)

[0.16730099 0.20250321 0.36342435 0.53451064 0.55576632 0.69591301
 0.8583327  0.86427055 0.87332423 0.98440461]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [35]:
x = np.arange(10)
np.add.reduce(x)


45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [36]:
A = np.random.randint(0,2,5)
print("A\n",A)
B = np.random.randint(0,2,5)
print("B\n",B)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print("using allclose\n",equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print("using array_equal\n",equal)

A
 [0 1 0 1 0]
B
 [1 0 1 1 0]
using allclose
 False
using array_equal
 False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [37]:
x = np.zeros(10)
x.flags.writeable = False
x[0] = 1


ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [38]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


[0.27277282 1.08891134 0.54530882 0.71317754 0.8049369  0.84128927
 0.40005609 0.96415885 1.27755169 0.54273447]
[0.51122485 0.98927956 0.98033815 0.75800805 0.16471798 0.60455019
 0.02615544 0.41436949 0.69959637 0.86089809]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [39]:
Z = np.random.random(10)
print("Z\n",Z)
Z[Z.argmax()] = 0
print("replace max value by 0\n",Z)


Z
 [0.86296148 0.78787516 0.18090024 0.84080998 0.49618743 0.43235685
 0.68219754 0.80597654 0.59920214 0.44166   ]
replace max value by 0
 [0.         0.78787516 0.18090024 0.84080998 0.49618743 0.43235685
 0.68219754 0.80597654 0.59920214 0.44166   ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [40]:
X = np.zeros((5,5), [('x',float),('y',float)])
X['x'], X['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(X)


[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [41]:
X = np.arange(8)
print("value of X\n",X)
Y = X + 0.5
print("value of Y\n",Y)
C = 1.0 / np.subtract.outer(X, Y)
print("value of C\n",C)
print("value linalg.det\n")
print(np.linalg.det(C))

value of X
 [0 1 2 3 4 5 6 7]
value of Y
 [0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5]
value of C
 [[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]
value linalg.det

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [42]:
for dtype in [np.int8, np.int32, np.int64]:
   print("using iinfo min\n",np.iinfo(dtype).min)
   print("using iinfo max\n",np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print("finfo min\n",np.finfo(dtype).min)
   print("finfo max\n",np.finfo(dtype).max)
   print("finfo eps\n",np.finfo(dtype).eps)


using iinfo min
 -128
using iinfo max
 127
using iinfo min
 -2147483648
using iinfo max
 2147483647
using iinfo min
 -9223372036854775808
using iinfo max
 9223372036854775807
finfo min
 -3.4028235e+38
finfo max
 3.4028235e+38
finfo eps
 1.1920929e-07
finfo min
 -1.7976931348623157e+308
finfo max
 1.7976931348623157e+308
finfo eps
 2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [43]:
np.set_printoptions(threshold=float("inf"))
x = np.zeros((40,40))
print(x)


[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [44]:
x= np.arange(100)
print("value of x\n",x)
y= np.random.uniform(0,100)
print("value of y\n",y)
index = (np.abs(x-y)).argmin()
print("value of argmin x,y \n",index)
print("index of argamin value\n",x[index])

value of x
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
value of y
 46.0708628703536
value of argmin x,y 
 46
index of argamin value
 46


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [45]:
a= np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(a)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [46]:
Z = np.random.random((10,2))
print("val of Z\n",Z)
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
print("val of X \n",X)
print("val of Y \n",Y)
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print("np.sqrt( (X-X.T)**2 + (Y-Y.T)**2) ans==")
print(D)



val of Z
 [[0.86574755 0.58433061]
 [0.78227859 0.49597966]
 [0.65853651 0.08443745]
 [0.87891331 0.40813561]
 [0.99024854 0.96272868]
 [0.47890977 0.22351925]
 [0.28356576 0.12242157]
 [0.41667985 0.56641451]
 [0.89501644 0.69467357]
 [0.72013887 0.3473838 ]]
val of X 
 [[0.86574755 0.78227859 0.65853651 0.87891331 0.99024854 0.47890977
  0.28356576 0.41667985 0.89501644 0.72013887]]
val of Y 
 [[0.58433061 0.49597966 0.08443745 0.40813561 0.96272868 0.22351925
  0.12242157 0.56641451 0.69467357 0.3473838 ]]
np.sqrt( (X-X.T)**2 + (Y-Y.T)**2) ans==
[[0.         0.12154405 0.5411373  0.1766862  0.39835361 0.528988
  0.74316592 0.44942495 0.11415882 0.2781109 ]
 [0.12154405 0.         0.42974305 0.13059421 0.51098547 0.4077589
  0.62310523 0.37232178 0.22844932 0.16106543]
 [0.5411373  0.42974305 0.         0.39159473 0.93884416 0.22717727
  0.37688971 0.53925553 0.65445464 0.27006598]
 [0.1766862  0.13059421 0.39159473 0.         0.56565803 0.44055197
  0.66035688 0.4885816  0.28699009 

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [47]:
Z = (np.random.rand(10)*100).astype(np.float32)
print("val of z\n",Z)
Y = Z.view(np.int32)
print("val of Y\n",Y)
Y[:] = Z
print("val of 32 bit integer1`")
print(Y)

val of z
 [44.560738  69.95912   46.924076  87.02099   55.095825   0.6409804
 12.428393  99.01546   56.61644    3.7228842]
val of Y
 [1110588978 1116465938 1111208513 1118702271 1113350688 1059329867
 1095162547 1120274410 1113749308 1080968124]
val of 32 bit integer1`
[44 69 46 87 55  0 12 99 56  3]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [48]:
from io import StringIO

# make file readable using string id
a = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
x = np.genfromtxt(a, delimiter=",", dtype=np.int)
print("using genfromtxt read file like below:::\n",x)


using genfromtxt read file like below:::
 [[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [49]:
x = np.arange(9).reshape(3,3)
print("3*3 matix\n",x)
for index, value in np.ndenumerate(x):
    print("using ndenumerate get index and value\n",index, value)
for index in np.ndindex(x.shape):
    print("using ndindex get index and value\n",index, x[index])

3*3 matix
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
using ndenumerate get index and value
 (0, 0) 0
using ndenumerate get index and value
 (0, 1) 1
using ndenumerate get index and value
 (0, 2) 2
using ndenumerate get index and value
 (1, 0) 3
using ndenumerate get index and value
 (1, 1) 4
using ndenumerate get index and value
 (1, 2) 5
using ndenumerate get index and value
 (2, 0) 6
using ndenumerate get index and value
 (2, 1) 7
using ndenumerate get index and value
 (2, 2) 8
using ndindex get index and value
 (0, 0) 0
using ndindex get index and value
 (0, 1) 1
using ndindex get index and value
 (0, 2) 2
using ndindex get index and value
 (1, 0) 3
using ndindex get index and value
 (1, 1) 4
using ndindex get index and value
 (1, 2) 5
using ndindex get index and value
 (2, 0) 6
using ndindex get index and value
 (2, 1) 7
using ndindex get index and value
 (2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [50]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
print("####using meshgrid and linespace create X,Y #####\n",X,Y)
D = np.sqrt(X*X+Y*Y)
print("####np.sqrt(X*X+Y*Y)\n####",D)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print("####2D Gaussian like array####\n",G)

####using meshgrid and linespace create X,Y #####
 [[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [51]:
n = 10
p = 3
x = np.zeros((n,n))
print("random 2d array of 10\n",x)
np.put(x, np.random.choice(range(n*n), p, replace=False),1)
print("randomly placing p==3 and value of 1 in p times in 2d array \n",x)

random 2d array of 10
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
randomly placing p==3 and value of 1 in p times in 2d array 
 [[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [52]:
X = np.random.rand(5, 10)
print("random matrix\n",X)
Y = X - X.mean(axis=1, keepdims=True)
print("Substrating row of each row")
print(Y)

random matrix
 [[0.49234776 0.39528831 0.29120827 0.23608088 0.05321177 0.5257543
  0.27096305 0.74731324 0.18926965 0.12731916]
 [0.31070589 0.94967861 0.635842   0.26235506 0.33636341 0.97913679
  0.71468057 0.1716341  0.91529619 0.49599745]
 [0.36133979 0.21300279 0.71894479 0.67404563 0.46055239 0.50939285
  0.90925241 0.56112993 0.98131016 0.74439526]
 [0.63707161 0.31240108 0.8286332  0.08684139 0.79449145 0.74832443
  0.80198359 0.01738801 0.98624341 0.02901875]
 [0.80286589 0.86563075 0.89583291 0.72598699 0.7381974  0.80124892
  0.13393234 0.14993909 0.86904705 0.41120638]]
Substrating row of each row
[[ 0.15947212  0.06241267 -0.04166737 -0.09679476 -0.27966387  0.19287866
  -0.06191258  0.4144376  -0.14360599 -0.20555648]
 [-0.26646312  0.3725096   0.058673   -0.31481395 -0.2408056   0.40196778
   0.13751156 -0.4055349   0.33812719 -0.08117156]
 [-0.25199681 -0.40033381  0.10560819  0.06070903 -0.15278421 -0.10394375
   0.29591581 -0.05220667  0.36797356  0.13105866]
 [ 0.11

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [53]:
x = np.random.randint(0,10,(3,3))
print("unsorted matrix\n",x)
print("sorted matris using argsort\n",x[x[:,1].argsort()])

unsorted matrix
 [[0 3 1]
 [7 0 8]
 [2 5 0]]
sorted matris using argsort
 [[7 0 8]
 [0 3 1]
 [2 5 0]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [54]:
x = np.random.randint(0,3,(3,10))
print((~x.any(axis=0)).any())

True


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [55]:
x = np.random.uniform(0,1,10)
print("array\n",x)
y = 0.5
print("\ngiven y ==",y)


m = x.flat[np.abs(x - y).argmin()]
print("\nprint nearest value of y in array\n",m)

array
 [0.70655542 0.86019052 0.03821738 0.92940608 0.31823246 0.59473446
 0.62702388 0.12403729 0.48260226 0.86963241]

given y == 0.5

print nearest value of y in array
 0.48260225523739764


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [56]:
A = np.arange(3).reshape(3,1)
print("3*1 matrix A\n",A)
B = np.arange(3).reshape(1,3)
print("1*3 matrix B\n",B)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print("sum of A and B using iterator\n",it.operands[2])

3*1 matrix A
 [[0]
 [1]
 [2]]
1*3 matrix B
 [[0 1 2]]
sum of A and B using iterator
 [[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [57]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [58]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print("using bincount\n",Z)
np.add.at(Z, I, 1)
print("using add.at\n",Z)


using bincount
 [2. 2. 2. 3. 2. 4. 7. 3. 4. 1.]
using add.at
 [ 3.  3.  3.  5.  3.  7. 13.  5.  7.  1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [59]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print("using bincounrt\n",F)


using bincounrt
 [0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [60]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)


64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [61]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print("sum using axix\n",sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print("sum using reshape and axis\n",sum)


sum using axix
 [[52 45 48 43]
 [56 61 61 52]
 [68 39 43 28]]
sum using reshape and axis
 [[52 45 48 43]
 [56 61 61 52]
 [68 39 43 28]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [62]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print("mean of subset\n",D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print("using series\n",pd.Series(D).groupby(S).mean())


mean of subset
 [0.50418094 0.56428747 0.62939649 0.56410934 0.53986467 0.52161818
 0.42296163 0.34497537 0.49052086 0.57051435]
using series
 0    0.504181
1    0.564287
2    0.629396
3    0.564109
4    0.539865
5    0.521618
6    0.422962
7    0.344975
8    0.490521
9    0.570514
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [63]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
print("using dot method\n",np.diag(np.dot(A, B)))

# Fast version
print("using sum method\n",np.sum(A * B.T, axis=1))

# Faster version
print("using einum method\n",np.einsum("ij,ji->i", A, B))


using dot method
 [1.3972058  1.40137884 0.92267216 1.80659394 1.55974593]
using sum method
 [1.3972058  1.40137884 0.92267216 1.80659394 1.55974593]
using einum method
 [1.3972058  1.40137884 0.92267216 1.80659394 1.55974593]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [64]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print("bulding new vector\n",Z0)


bulding new vector
 [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [65]:
A = np.ones((5,5,3))
print("matrix 5,5,3\n",A)
B = 2*np.ones((5,5))
print("matrix 5,5\n",B)
print("multiplay both\n",A * B[:,:,None])


matrix 5,5,3
 [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
matrix 5,5
 [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
multiplay both
 [[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [66]:
A = np.arange(25).reshape(5,5)
print("normal array\n",A)
A[[0,1]] = A[[1,0]]
print("swaping first two row\n", A)


normal array
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
swaping first two row
 [[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [67]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 4, 10) ( 4, 58) ( 5, 17) ( 5, 77) ( 6, 75) ( 6, 85) (10, 45) (10, 58)
 (10, 79) (12, 22) (12, 90) (14, 37) (14, 88) (17, 42) (17, 49) (17, 77)
 (22, 90) (34, 36) (34, 75) (36, 75) (37, 88) (42, 49) (45, 79) (67, 73)
 (67, 88) (73, 88) (75, 75) (75, 79) (75, 85)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [68]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print("bincount of A\n",A)


bincount of A
 [1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [69]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [70]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)


[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [71]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)
print("using np.logical\n",Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)
print("using np.negative\n",Z)


using np.logical
 [1 1 1 0 0 1 1 1 0 0 0 0 1 0 0 0 1 1 1 0 0 1 0 1 1 0 0 0 1 0 1 0 0 0 0 0 1
 1 0 0 1 0 1 1 0 0 1 0 0 1 1 1 1 0 0 1 0 1 1 0 0 0 0 0 0 1 1 0 1 0 1 1 1 1
 0 1 1 0 1 1 1 1 0 0 1 0 1 1 1 0 0 0 1 1 1 0 0 0 1 1]
using np.negative
 [ 6.27516336e-01 -5.54622487e-01 -4.91524834e-01 -5.98907673e-01
  4.60823747e-01  1.01892009e-02  1.94442824e-01  6.53125102e-01
 -6.57509554e-01 -7.10657283e-01  9.70000467e-01  7.92881719e-01
  4.82050448e-01 -4.20259455e-01 -2.02400326e-01  7.71218625e-01
 -4.08810450e-01  1.59573635e-01  9.49827027e-01  7.18174377e-01
  9.15879826e-01 -6.68306083e-02 -4.75742786e-01  7.68980918e-01
  5.65882213e-01 -1.67083416e-01  4.55942642e-01 -7.55019537e-04
  4.50080986e-01 -4.48193434e-02 -5.53333458e-01 -8.15978719e-01
 -1.53445783e-02 -8.92168363e-01  6.00716797e-01 -7.24784297e-01
  1.39791059e-01 -4.70451104e-01 -2.43747929e-01 -7.28568567e-01
  5.72656224e-01  8.21827328e-01  6.77224420e-02 -3.82797665e-01
 -4.91460890e-01 -9.37619877e-01 -1.41542378

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [72]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 2.98657694  0.78118688  7.52827682 11.239082    2.76999727  2.56300918
  5.8108995  10.50659835  5.25503571  0.73287387]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [73]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))


[[ 1.57515265 15.87808927  7.60392701 12.45215048  6.66920822 10.07469857
   4.00914597  5.72240492  8.85596289  3.1705644 ]
 [ 6.71092626  2.90025709  6.22623525  7.62805149 15.19918118 13.393573
  19.18227974 15.77583105 12.88755592 20.6685006 ]
 [ 8.31545351  1.42257489  7.36638307  8.15840483 15.4487556  13.23432651
  18.27266716 16.09175773 11.70442254 20.04305391]
 [ 3.73446235  0.97710958  2.09121906  2.99687363 10.55574362  8.93144418
  15.69049825 11.12488946 10.01674236 16.70154785]
 [ 1.2872551   1.2074187   3.38023463  2.0992877   5.83607248  4.94758715
  13.65785838  6.30644871  8.94714923 13.82851006]
 [ 2.60635608  2.45857317  4.30182826  2.50688514  5.66345963  5.11556615
  14.44600659  6.07838651  9.95927742 14.38263728]
 [ 3.36214511  6.34113424  8.95124866 10.18209279  2.96482598  4.49496954
   4.33058756  2.3458476   0.20391719  4.23916446]
 [ 3.55693455  0.70470974  1.77629658  2.59733881 10.13745342  8.50445771
  15.30713271 10.71005941  9.67425363 16.29159826]
 [

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [74]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)


[[1 3 4 6 5 6 6 3 4 8]
 [8 6 6 0 5 4 7 7 1 7]
 [9 8 9 1 5 5 4 1 2 6]
 [9 9 3 9 7 2 0 3 6 1]
 [5 8 3 2 6 2 6 7 2 1]
 [5 6 9 5 9 0 5 6 0 9]
 [4 0 2 5 4 3 9 2 7 2]
 [5 9 6 5 6 1 1 4 0 9]
 [5 1 7 5 7 6 9 5 2 8]
 [3 3 7 6 3 2 8 7 5 7]]
[[0 0 0 0 0]
 [0 1 3 4 6]
 [0 8 6 6 0]
 [0 9 8 9 1]
 [0 9 9 3 9]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [75]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [76]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)


10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [77]:
x = np.random.randint(0,10,50)
print(np.bincount(x).argmax())

3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [78]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[4 4 1]
   [4 4 4]
   [0 3 4]]

  [[4 1 4]
   [4 4 2]
   [3 4 2]]

  [[1 4 3]
   [4 2 4]
   [4 2 2]]

  [[4 3 3]
   [2 4 4]
   [2 2 1]]

  [[3 3 0]
   [4 4 2]
   [2 1 1]]

  [[3 0 4]
   [4 2 1]
   [1 1 0]]

  [[0 4 1]
   [2 1 3]
   [1 0 3]]

  [[4 1 1]
   [1 3 3]
   [0 3 2]]]


 [[[4 4 4]
   [0 3 4]
   [4 3 4]]

  [[4 4 2]
   [3 4 2]
   [3 4 4]]

  [[4 2 4]
   [4 2 2]
   [4 4 2]]

  [[2 4 4]
   [2 2 1]
   [4 2 1]]

  [[4 4 2]
   [2 1 1]
   [2 1 2]]

  [[4 2 1]
   [1 1 0]
   [1 2 2]]

  [[2 1 3]
   [1 0 3]
   [2 2 3]]

  [[1 3 3]
   [0 3 2]
   [2 3 3]]]


 [[[0 3 4]
   [4 3 4]
   [0 2 2]]

  [[3 4 2]
   [3 4 4]
   [2 2 3]]

  [[4 2 2]
   [4 4 2]
   [2 3 1]]

  [[2 2 1]
   [4 2 1]
   [3 1 1]]

  [[2 1 1]
   [2 1 2]
   [1 1 1]]

  [[1 1 0]
   [1 2 2]
   [1 1 3]]

  [[1 0 3]
   [2 2 3]
   [1 3 0]]

  [[0 3 2]
   [2 3 3]
   [3 0 2]]]


 [[[4 3 4]
   [0 2 2]
   [1 1 1]]

  [[3 4 4]
   [2 2 3]
   [1 1 2]]

  [[4 4 2]
   [2 3 1]
   [1 2 0]]

  [[4 2 1]
   [3 1 1]
   [2 0 0]]

  [[2 1 2]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [79]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)


[[ 1 14 17 16 11]
 [14  9 14 11  8]
 [17 14  4 42 12]
 [16 11 42  1  7]
 [11  8 12  7  8]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [80]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [81]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)


[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [82]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0
  0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [83]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [84]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [85]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [86]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

4.14 s ± 354 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
254 ms ± 35.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
134 ms ± 12.7 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [87]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)


[4 5 7]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [88]:
Z = np.random.randint(0,5,(10,3))
print("array of Z\n",Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print("array of dtypes\n",U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print("numerical array \n",U)


array of Z
 [[0 4 3]
 [1 4 4]
 [3 3 1]
 [4 2 0]
 [0 2 1]
 [1 3 3]
 [3 2 4]
 [3 2 3]
 [1 1 2]
 [3 2 2]]
array of dtypes
 [[0 4 3]
 [1 4 4]
 [3 3 1]
 [4 2 0]
 [0 2 1]
 [1 3 3]
 [3 2 4]
 [3 2 3]
 [1 1 2]
 [3 2 2]]
numerical array 
 [[0 4 3]
 [1 4 4]
 [3 3 1]
 [4 2 0]
 [0 2 1]
 [1 3 3]
 [3 2 4]
 [3 2 3]
 [1 1 2]
 [3 2 2]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [89]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [90]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)


[[0 0 0]
 [0 0 1]
 [1 0 1]
 [1 1 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [91]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.21793708, 0.52358594, 0.10221722, 0.05458698, 0.23191329,
        0.44951944, 0.23620806, 0.20455932, 0.14818221, 0.12405858],
       [0.21525626, 0.51714537, 0.10095986, 0.05391551, 0.22906055,
        0.44398995, 0.2333025 , 0.20204306, 0.14635944, 0.12253255],
       [0.38127327, 0.91599524, 0.17882544, 0.095498  , 0.40572416,
        0.78641848, 0.41323772, 0.35786935, 0.25923958, 0.21703613],
       [0.03471551, 0.08340275, 0.01628233, 0.00869524, 0.0369418 ,
        0.07160459, 0.03762592, 0.03258455, 0.02360416, 0.01976147],
       [0.23354355, 0.56107992, 0.10953699, 0.05849595, 0.24852059,
        0.48170952, 0.25312292, 0.21920781, 0.15879354, 0.13294241],
       [0.19260456, 0.46272548, 0.09033572, 0.04824191, 0.2049562 ,
        0.3972683 , 0.20875177, 0.1807818 , 0.13095784, 0.10963828],
       [0.3238894 , 0.77813256, 0.15191116, 0.08112499, 0.34466029,
        0.66805787, 0.35104301, 0.30400791, 0.2202225 , 0.18437091],
       [0.40703677, 0.97789111, 0.1909090

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [92]:
phi = np.arange(0, 10*np.pi, 0.1)

a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [93]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])


[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [94]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)


[-0.01446115  0.38970597]
