<a href="https://colab.research.google.com/github/omkarmohite123/omkarmohite123/blob/main/100_questions_on_Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>








 # Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)
np.show_config()


1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
x = np.zeros(10)
print(x)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
x = np.arange(10)
print(x)
print("size ==",x.size)
print("memory size ==",x.itemsize)

[0 1 2 3 4 5 6 7 8 9]
size == 10
memory size == 8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
import numpy as np
np.info(np.add)


add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
x=np.zeros(10)
x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
x=np.arange(10,49)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
x[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
x=np.arange(9).reshape(3, 3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
x=[1,2,0,0,4,0]
a=np.nonzero(x)
print(a)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
x=np.eye(3,3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
x=np.random.random((3,3,3))
print(x)

[[[0.30206404 0.98045573 0.34206757]
  [0.06256944 0.15391932 0.93578026]
  [0.47752012 0.15422507 0.99098205]]

 [[0.71866545 0.19517034 0.17774182]
  [0.19320131 0.24885577 0.38232097]
  [0.96339928 0.59082004 0.72751952]]

 [[0.18715943 0.98657171 0.09742618]
  [0.57946991 0.11472559 0.05139978]
  [0.23582413 0.06692476 0.1634683 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
x=np.random.random((10,10))
print("10*10 array ==\n",x)
print("min of array\n",x.min())
print("max of array\n",x.max())

10*10 array ==
 [[0.24445947 0.95462642 0.20821609 0.07384012 0.8371497  0.29529255
  0.85028361 0.01781235 0.71350462 0.1986992 ]
 [0.07609811 0.42315964 0.03386436 0.65952074 0.9727474  0.5744949
  0.04209746 0.82779066 0.53650453 0.35626708]
 [0.36357591 0.78047133 0.89653492 0.71747397 0.02393429 0.22733674
  0.94867279 0.26910838 0.37803149 0.08719544]
 [0.0423923  0.91599178 0.86289257 0.62991623 0.23551993 0.52278033
  0.20331624 0.02309574 0.23413545 0.10535298]
 [0.22469627 0.91078395 0.32607083 0.2991805  0.23400477 0.13598827
  0.47818446 0.90383051 0.71386053 0.92829029]
 [0.87843949 0.88837355 0.88103357 0.62638825 0.09834073 0.79522058
  0.17281182 0.07575002 0.51592751 0.10977362]
 [0.95669531 0.38416456 0.14785165 0.2900415  0.29562968 0.97761494
  0.93310098 0.68228585 0.2377828  0.22201301]
 [0.79983202 0.68404765 0.17515603 0.72740104 0.49149219 0.4136332
  0.81775428 0.15487628 0.1007511  0.59757645]
 [0.72839541 0.60762325 0.49857902 0.37714435 0.42291595 0.3332074

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)


```
`# This is formatted as code`
```



In [ ]:
x=np.random.random((30))
print("random vector of size 30\n",x)
print("mean value is\n",x.mean())

random vector of size 30
 [0.04649649 0.31473644 0.71528722 0.46445924 0.75778475 0.99870504
 0.57224243 0.37777871 0.64862867 0.83715623 0.19898336 0.10182997
 0.68944752 0.93100313 0.53582634 0.94153172 0.83645544 0.1738195
 0.31956772 0.715544   0.02629237 0.53224128 0.21274937 0.56600031
 0.60071485 0.22762103 0.34775549 0.76649827 0.68281736 0.28647751]
mean value is
 0.5142150585808037


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
x=np.ones((10,10))
x[1:-1,1:-1] = 0
print(x)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
x = np.ones((5,5))
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
x = np.diag(1+np.arange(4),k=-1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
x = np.zeros((8,8),dtype=int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
print(np.unravel_index(99,(6,7,8)))


(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
x= np.random.random((5,5))
print("value of random matrix ==",x)
min=x.min()
max=x.max()
k=(x-min)/(max-min)
print("ans of  (x-min)/(max-min)\n",k)


value of random matrix == [[0.484617   0.70351224 0.97188587 0.77414889 0.89505519]
 [0.55320557 0.04922488 0.53272927 0.34931657 0.38893137]
 [0.51497834 0.12888899 0.64803364 0.65083759 0.73110198]
 [0.90654377 0.22495808 0.10337995 0.1351345  0.52796638]
 [0.8911537  0.26398903 0.82581541 0.55432848 0.74036895]]
ans of  (x-min)/(max-min)
 [[0.47188742 0.70913083 1.         0.78568837 0.91672924]
 [0.5462252  0.         0.52403255 0.32524589 0.36818126]
 [0.50479371 0.08634169 0.64900193 0.65204091 0.7390332 ]
 [0.92918081 0.19046346 0.05869444 0.09311071 0.51887043]
 [0.91250073 0.23276605 0.84168567 0.54744224 0.74907694]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
import numpy as np

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
x = np.ones((5,3)) @ np.ones((3,2))
print(x)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
x = np.arange(11)
x[(3 < x) & (x < 8)] *= -1
print(x)


[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)


[[1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
[[False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]
 [False False False False False False False False]]
[[0.+0.j 0.+1.j 0.+0.j 0.+1.j 0.+0.j 0.+1.j 0.+0.j 0.+1.j]
 [0.+1.j 0.+0.j 0.+1.j 0.+0.j 0.+1.j 0.+0.j 0.+1.j 0.+0.j]
 [0.+0.j 0.+1.j 0.+0.j 0.+1.j 0.+0.j 0.+1.j 0.+0.j 0.+1.j]
 [0.+1.j 0.+0.j 0.+1.j 0.+0.j 0.+1.j 0.+0.j 0.+1.j 0.+0.j]
 [0.+0.j 0.+1.j 0.+0.j 0.+1.j 0.+0.j 0.+1.j 0.+0.

ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
x = np.random.uniform(-10,+10,10)
print("random x\n",x)
print(np.copysign(np.ceil(np.abs(x)), x))



#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
x1 = np.random.randint(0,8,10)
x2 = np.random.randint(0,8,10)
print("common values are",np.intersect1d(x1,x2))


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
#using np.seterr
defaults = np.seterr(all="ignore")
x = np.ones(1) / 0
print(x)
#back to sanity
_ = np.seterr(**defaults)
#using np.errstate
with np.errstate(all="ignore"):
    np.arange(3) / 0


#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1))
print(np.emath.sqrt(-1))
np.sqrt(-1) == np.emath.sqrt(-1)


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday = np.datetime64('today') - np.timedelta64(1)
print("yesterday date ==",yesterday)
today     = np.datetime64('today')
print("today date ==",today)
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print("tomarrow date",tomorrow)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(3)*1
print("A\n",A)
B = np.ones(3)*2
print("B\n",B)
add=np.add(A,B,out=B)
print("add (A+B)\n",add)
divide =np.divide(A,2,out=A)
print("(A/2)\n",divide)
negative=np.negative(A,out=A)
print("-1 * (A/2)\n",negative)
multiply=np.multiply(A,B,out=A)
print("((A+B)*(-A/2))\n",multiply)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
x= np.random.uniform(0,10,10)
print("random array\n",x)
print("% method\n",x - x%1)
print("using floor\n",np.floor(x))
print("using ceil\n",np.ceil(x))
print("using astype\n",x.astype(int))
print("using trunc\n",np.trunc(Z))

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
x=np.zeros((5,5))
x+=np.arange(5)
print(x)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
    for x in range(10):
        yield x
x = np.fromiter(generate(),dtype=float,count=-1)
print(x)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
x = np.linspace(0,1,11,endpoint=False)[1:]
print(x)


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
x = np.random.random(10)
x.sort()
print(x)

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
x = np.arange(10)
np.add.reduce(x)


#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A = np.random.randint(0,2,5)
print("A\n",A)
B = np.random.randint(0,2,5)
print("B\n",B)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print("using allclose\n",equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print("using array_equal\n",equal)

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
x = np.zeros(10)
x.flags.writeable = False
x[0] = 1


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
Z = np.random.random(10)
print("Z\n",Z)
Z[Z.argmax()] = 0
print("replace max value by 0\n",Z)


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
X = np.zeros((5,5), [('x',float),('y',float)])
X['x'], X['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(X)


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
X = np.arange(8)
print("value of X\n",X)
Y = X + 0.5
print("value of Y\n",Y)
C = 1.0 / np.subtract.outer(X, Y)
print("value of C\n",C)
print("value linalg.det\n")
print(np.linalg.det(C))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print("using iinfo min\n",np.iinfo(dtype).min)
   print("using iinfo max\n",np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print("finfo min\n",np.finfo(dtype).min)
   print("finfo max\n",np.finfo(dtype).max)
   print("finfo eps\n",np.finfo(dtype).eps)


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold=float("inf"))
x = np.zeros((40,40))
print(x)


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
x= np.arange(100)
print("value of x\n",x)
y= np.random.uniform(0,100)
print("value of y\n",y)
index = (np.abs(x-y)).argmin()
print("value of argmin x,y \n",index)
print("index of argamin value\n",x[index])

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
a= np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(a)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
Z = np.random.random((10,2))
print("val of Z\n",Z)
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
print("val of X \n",X)
print("val of Y \n",Y)
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print("np.sqrt( (X-X.T)**2 + (Y-Y.T)**2) ans==")
print(D)



#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
Z = (np.random.rand(10)*100).astype(np.float32)
print("val of z\n",Z)
Y = Z.view(np.int32)
print("val of Y\n",Y)
Y[:] = Z
print("val of 32 bit integer1`")
print(Y)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

# make file readable using string id
a = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
x = np.genfromtxt(a, delimiter=",", dtype=np.int)
print("using genfromtxt read file like below:::\n",x)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
x = np.arange(9).reshape(3,3)
print("3*3 matix\n",x)
for index, value in np.ndenumerate(x):
    print("using ndenumerate get index and value\n",index, value)
for index in np.ndindex(x.shape):
    print("using ndindex get index and value\n",index, x[index])

3*3 matix
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
using ndenumerate get index and value
 (0, 0) 0
using ndenumerate get index and value
 (0, 1) 1
using ndenumerate get index and value
 (0, 2) 2
using ndenumerate get index and value
 (1, 0) 3
using ndenumerate get index and value
 (1, 1) 4
using ndenumerate get index and value
 (1, 2) 5
using ndenumerate get index and value
 (2, 0) 6
using ndenumerate get index and value
 (2, 1) 7
using ndenumerate get index and value
 (2, 2) 8
using ndindex get index and value
 (0, 0) 0
using ndindex get index and value
 (0, 1) 1
using ndindex get index and value
 (0, 2) 2
using ndindex get index and value
 (1, 0) 3
using ndindex get index and value
 (1, 1) 4
using ndindex get index and value
 (1, 2) 5
using ndindex get index and value
 (2, 0) 6
using ndindex get index and value
 (2, 1) 7
using ndindex get index and value
 (2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
print("####using meshgrid and linespace create X,Y #####\n",X,Y)
D = np.sqrt(X*X+Y*Y)
print("####np.sqrt(X*X+Y*Y)\n####",D)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print("####2D Gaussian like array####\n",G)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n = 10
p = 3
x = np.zeros((n,n))
print("random 2d array of 10\n",x)
np.put(x, np.random.choice(range(n*n), p, replace=False),1)
print("randomly placing p==3 and value of 1 in p times in 2d array \n",x)

random 2d array of 10
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
randomly placing p==3 and value of 1 in p times in 2d array 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
X = np.random.rand(5, 10)
print("random matrix\n",X)
Y = X - X.mean(axis=1, keepdims=True)
print("Substrating row of each row")
print(Y)

random matrix
 [[0.26768061 0.44880873 0.24000977 0.38262431 0.0059107  0.75607045
  0.71012853 0.75540106 0.66747455 0.41597925]
 [0.6768943  0.55493772 0.65299988 0.98495058 0.74133686 0.30826642
  0.04854461 0.21313217 0.52004299 0.75096528]
 [0.4593664  0.72754788 0.04630489 0.89106749 0.00989757 0.57383887
  0.98503169 0.20419982 0.21261588 0.7544121 ]
 [0.18473591 0.48632757 0.07337152 0.30343198 0.46352338 0.58797111
  0.58916104 0.70518561 0.98927496 0.30123152]
 [0.80826759 0.64622753 0.24246678 0.89950871 0.84699249 0.14681586
  0.56040294 0.24797604 0.6846537  0.31184793]]
Substrating row of each row
[[-0.19732818 -0.01620007 -0.22499902 -0.08238449 -0.4590981   0.29106165
   0.24511973  0.29039226  0.20246575 -0.04902954]
 [ 0.13168722  0.00973064  0.1077928   0.4397435   0.19612978 -0.23694066
  -0.49666247 -0.33207491 -0.0251641   0.2057582 ]
 [-0.02706186  0.24111962 -0.44012337  0.40463923 -0.47653069  0.08741061
   0.49860343 -0.28222844 -0.27381238  0.26798384]
 [-0.2

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
x = np.random.randint(0,10,(3,3))
print("unsorted matrix\n",x)
print("sorted matris using argsort\n",x[x[:,1].argsort()])

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
x = np.random.randint(0,3,(3,10))
print((~x.any(axis=0)).any())

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
x = np.random.uniform(0,1,10)
print("array\n",x)
y = 0.5
print("\ngiven y ==",y)


m = x.flat[np.abs(x - y).argmin()]
print("\nprint nearest value of y in array\n",m)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
A = np.arange(3).reshape(3,1)
print("3*1 matrix A\n",A)
B = np.arange(3).reshape(1,3)
print("1*3 matrix B\n",B)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print("sum of A and B using iterator\n",it.operands[2])

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print("using bincount\n",Z)
np.add.at(Z, I, 1)
print("using add.at\n",Z)


using bincount
 [3. 2. 2. 3. 5. 4. 3. 4. 2. 2.]
using add.at
 [5. 3. 3. 5. 9. 7. 5. 7. 3. 3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print("using bincounrt\n",F)


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)


64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print("sum using axix\n",sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print("sum using reshape and axis\n",sum)


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print("mean of subset\n",D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print("using series\n",pd.Series(D).groupby(S).mean())


mean of subset
 [0.54188181 0.39088546 0.6101259  0.4391576  0.48336223 0.62745227
 0.61511274 0.54337859 0.5294657  0.41246668]
using series
 0    0.541882
1    0.390885
2    0.610126
3    0.439158
4    0.483362
5    0.627452
6    0.615113
7    0.543379
8    0.529466
9    0.412467
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
print("using dot method\n",np.diag(np.dot(A, B)))

# Fast version
print("using sum method\n",np.sum(A * B.T, axis=1))

# Faster version
print("using einum method\n",np.einsum("ij,ji->i", A, B))


using dot method
 [0.74825532 2.03664425 1.47940601 2.26048941 1.16554264]
using sum method
 [0.74825532 2.03664425 1.47940601 2.26048941 1.16554264]
using einum method
 [0.74825532 2.03664425 1.47940601 2.26048941 1.16554264]


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print("bulding new vector\n",Z0)


bulding new vector
 [1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
A = np.ones((5,5,3))
print("matrix 5,5,3\n",A)
B = 2*np.ones((5,5))
print("matrix 5,5\n",B)
print("multiplay both\n",A * B[:,:,None])


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
A = np.arange(25).reshape(5,5)
print("normal array\n",A)
A[[0,1]] = A[[1,0]]
print("swaping first two row\n", A)


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2, 43) ( 2, 58) ( 7,  9) ( 7, 23) ( 9, 23) (10, 41) (10, 97) (16, 49)
 (16, 53) (19, 21) (19, 38) (21, 38) (26, 31) (26, 56) (30, 74) (30, 93)
 (31, 56) (36, 43) (36, 80) (38, 59) (38, 90) (41, 97) (43, 47) (43, 58)
 (43, 80) (43, 99) (47, 99) (49, 53) (59, 90) (74, 93)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print("bincount of A\n",A)


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)


[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)
print("using np.logical\n",Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)
print("using np.negative\n",Z)


using np.logical
 [0 0 1 1 1 1 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 0 1 0 1 0 0 0
 1 0 0 0 0 1 0 1 1 0 1 1 1 0 1 1 0 0 0 1 1 1 0 1 0 0 1 1 0 0 1 1 0 1 1 1 0
 1 1 0 1 1 0 0 1 1 1 1 1 0 1 0 1 0 1 1 0 0 0 1 1 0 1]
using np.negative
 [ 0.24495724  0.87343623  0.01170844 -0.5603918   0.80013281 -0.20397049
  0.19067962  0.2859748   0.32501484  0.10608032 -0.49942473  0.35438831
  0.8994884   0.94047729 -0.56381349 -0.33204674  0.25107255 -0.42594171
 -0.66792597  0.96707446 -0.22737852 -0.18925837  0.71860605  0.95203411
 -0.66947094  0.18334208  0.70920979 -0.53536363 -0.15605537  0.73849562
  0.41754445  0.97228241 -0.0765341   0.84980649  0.18325699 -0.23029329
 -0.39110624  0.93172189  0.7070462  -0.93698746  0.49425808  0.08161283
 -0.14269441  0.85602732  0.74295048 -0.62280398  0.56195834  0.66967048
 -0.96165631 -0.68248042  0.08263702  0.19474336 -0.26063491  0.29334196
  0.73576306 -0.53797431 -0.72591845 -0.34527665  0.70827444 -0.2477992
 -0.25872776 -0.12651997 -0.05

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))


NameError: ignored

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)


[[7 7 5 3 6 6 8 0 9 3]
 [1 1 0 5 7 4 6 4 6 7]
 [3 3 1 4 5 0 7 8 5 3]
 [5 0 6 8 0 0 8 6 2 5]
 [1 4 9 1 4 8 9 2 3 3]
 [2 0 4 9 1 2 3 0 1 1]
 [7 8 5 2 9 7 2 5 8 4]
 [9 9 9 0 6 3 8 4 8 4]
 [0 8 1 3 7 1 9 7 6 8]
 [0 8 2 8 7 0 0 0 9 9]]
[[0 0 0 0 0]
 [0 7 7 5 3]
 [0 1 1 0 5]
 [0 3 3 1 4]
 [0 5 0 6 8]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)


10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
x = np.random.randint(0,10,50)
print(np.bincount(x).argmax())

7


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[3 0 4]
   [2 1 2]
   [4 1 2]]

  [[0 4 2]
   [1 2 0]
   [1 2 0]]

  [[4 2 0]
   [2 0 4]
   [2 0 4]]

  [[2 0 0]
   [0 4 4]
   [0 4 1]]

  [[0 0 3]
   [4 4 0]
   [4 1 0]]

  [[0 3 1]
   [4 0 1]
   [1 0 1]]

  [[3 1 2]
   [0 1 1]
   [0 1 0]]

  [[1 2 1]
   [1 1 4]
   [1 0 3]]]


 [[[2 1 2]
   [4 1 2]
   [1 4 0]]

  [[1 2 0]
   [1 2 0]
   [4 0 4]]

  [[2 0 4]
   [2 0 4]
   [0 4 0]]

  [[0 4 4]
   [0 4 1]
   [4 0 0]]

  [[4 4 0]
   [4 1 0]
   [0 0 2]]

  [[4 0 1]
   [1 0 1]
   [0 2 1]]

  [[0 1 1]
   [0 1 0]
   [2 1 1]]

  [[1 1 4]
   [1 0 3]
   [1 1 1]]]


 [[[4 1 2]
   [1 4 0]
   [4 2 2]]

  [[1 2 0]
   [4 0 4]
   [2 2 0]]

  [[2 0 4]
   [0 4 0]
   [2 0 3]]

  [[0 4 1]
   [4 0 0]
   [0 3 1]]

  [[4 1 0]
   [0 0 2]
   [3 1 4]]

  [[1 0 1]
   [0 2 1]
   [1 4 4]]

  [[0 1 0]
   [2 1 1]
   [4 4 0]]

  [[1 0 3]
   [1 1 1]
   [4 0 3]]]


 [[[1 4 0]
   [4 2 2]
   [4 3 2]]

  [[4 0 4]
   [2 2 0]
   [3 2 4]]

  [[0 4 0]
   [2 0 3]
   [2 4 0]]

  [[4 0 0]
   [0 3 1]
   [4 0 4]]

  [[0 0 2]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)


[[ 9  3 17  9  1]
 [ 3  7 11  6  7]
 [17 11  8 42  3]
 [ 9  6 42  6  8]
 [ 1  7  3  8  2]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)


[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9996 9995 9997 9999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.8 s ± 19.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
204 ms ± 3.51 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
128 ms ± 11.1 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)


[0 2 4 5]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))
print("array of Z\n",Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print("array of dtypes\n",U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print("numerical array \n",U)


array of Z
 [[0 4 3]
 [4 2 0]
 [0 3 2]
 [4 1 2]
 [4 0 2]
 [1 0 1]
 [2 2 3]
 [1 1 0]
 [1 1 3]
 [3 1 4]]
array of dtypes
 [[0 4 3]
 [4 2 0]
 [0 3 2]
 [4 1 2]
 [4 0 2]
 [1 0 1]
 [2 2 3]
 [1 1 0]
 [1 1 3]
 [3 1 4]]
numerical array 
 [[0 4 3]
 [4 2 0]
 [0 3 2]
 [4 1 2]
 [4 0 2]
 [1 0 1]
 [2 2 3]
 [1 1 0]
 [1 1 3]
 [3 1 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)


[[0 0 1]
 [0 1 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[6.47035459e-05, 3.77888680e-02, 4.13180985e-02, 2.70701150e-01,
        1.60896820e-01, 1.16690964e-01, 1.98899333e-02, 8.76825544e-02,
        1.15906906e-01, 6.64571007e-02],
       [1.25416903e-05, 7.32473422e-03, 8.00881598e-03, 5.24708487e-02,
        3.11871328e-02, 2.26185737e-02, 3.85532785e-03, 1.69957832e-02,
        2.24665974e-02, 1.28815873e-02],
       [1.96553219e-04, 1.14793147e-01, 1.25514068e-01, 8.22322512e-01,
        4.88764371e-01, 3.54478016e-01, 6.04206518e-02, 2.66357710e-01,
        3.52096246e-01, 2.01880081e-01],
       [2.24900607e-04, 1.31348896e-01, 1.43616015e-01, 9.40919881e-01,
        5.59255167e-01, 4.05601704e-01, 6.91346663e-02, 3.04772472e-01,
        4.02876429e-01, 2.30995721e-01],
       [9.59181892e-05, 5.60191831e-02, 6.12510045e-02, 4.01294299e-01,
        2.38517556e-01, 1.72985665e-01, 2.94853451e-02, 1.29982858e-01,
        1.71823359e-01, 9.85177036e-02],
       [7.68234509e-06, 4.48672665e-03, 4.90575727e-03, 3.21407369e-02,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)

a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)


#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])


[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)


[-0.08810108  0.28707534]
